image:
  repository: acrvclusterpoc.azurecr.io/pyapp
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

env:
  APP_ENV: "dev"
  APP_MESSAGE: "Hello from AKS!"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  host: ""  # Will be set at runtime
  tlsEnabled: false
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80


