{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "pyapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pyapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations: {}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ printf "%s.%s" .Release.Namespace .Values.ingress.baseDomain | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "pyapp.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
