apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-deployer
spec:
  generators:
    - git:
        repoURL: https://github.com/bahram663/vcluster-deploy.git
        revision: main
        branches:
          - "main"
          - "feature-*"
  template:
    metadata:
      name: "{{branch}}-pyapp"
    spec:
      project: default
      source:
        repoURL: https://github.com/bahram663/vcluster-deploy.git
        targetRevision: "{{branch}}"
        path: helm/pyapp
        helm:
          values: |
            image:
              repository: acrvclusterpoc.azurecr.io/pyapp
              tag: "{{branch}}"
            ingress:
              enabled: true
              className: nginx
              host: "{{branch}}.test.bahram.az"
      destination:
        name: "{{branch}}-vcluster"
        namespace: pyapp
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
