apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-deployer
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/bahram663/vcluster-deploy.git
        revision: main
        branches:
          - "feature-*"
          - "dev"
          - "test"
  template:
    metadata:
      name: "{{branch}}-pyapp"
    spec:
      project: default
      source:
        repoURL: https://github.com/bahram663/vcluster-deploy.git
        path: helm/pyapp
        targetRevision: main
        helm:
          releaseName: "{{branch}}-pyapp"
          values: |
            image:
              repository: acrvclusterpoc.azurecr.io/pyapp
              tag: "{{branch}}"
            ingress:
              enabled: true
              className: nginx
              host: "{{branch}}.test.bahram.az"
      destination:
        server: https://{{branch}}-vcluster.default.svc.cluster.local
        namespace: pyapp
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
