apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-provisioner
  namespace: argocd
spec:
  generators:
    - scmProvider:
        github:
          # For a personal account, 'organization' is your GitHub username.
          organization: bahram663
          # We need all branches so we can filter to feature/*, dev, preprod, main, etc.
          allBranches: true
        # Only act on this one repo and the branches we care about:
        filters:
          - repositoryMatch: '^vcluster-deploy$'
            branchMatch: '^(main|dev|preprod|feature-.*)$'
  template:
    metadata:
      # Application name will be "<branch>-vcluster"
      name: '{{branch}}-vcluster'
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        # Namespace for the *host* objects of this vcluster (one per branch)
        namespace: '{{branch}}-vcluster'
      source:
        repoURL: https://charts.loft.sh
        chart: vcluster
        targetRevision: 0.20.0
        helm:
          releaseName: '{{branch}}'
          values: |
            syncer:
              extraArgs:
                # handy SAN for the vcluster’s API server if you later front it
                - --tls-san={{branch}}.vcluster.bahram.az
            ingress:
              enabled: true
              # This will be your host per branch (points to vcluster’s exposed service)
              host: "{{branch}}.vcluster.bahram.az"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          # Let ArgoCD create the destination namespace automatically
          - CreateNamespace=true
