apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vcluster-provisioner
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/bahram663/vcluster-deploy.git
        revision: main
        branches:
          - "feature-*"
  template:
    metadata:
      name: "{{branch}}-vcluster"
    spec:
      project: default
      source:
        repoURL: https://charts.loft.sh
        chart: vcluster
        targetRevision: 0.20.0
        helm:
          releaseName: "{{branch}}"
          values: |
            syncer:
              extraArgs:
                - --tls-san={{branch}}.vcluster.bahram.az
            ingress:
              enabled: true
              host: "{{branch}}.vcluster.bahram.az"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{branch}}-vcluster"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
