name: Cleanup on branch delete

on:
  delete:
    branches: ["*"]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      RG: ${{ vars.AZURE_RESOURCE_GROUP }}
      AKS: ${{ vars.AZURE_AKS_CLUSTER }}
    steps:
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Set kubectl context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.RG }}
          cluster-name: ${{ env.AKS }}

      - name: Delete release and namespace
        run: |
          NS=$(echo "${GITHUB_REF_NAME}" | tr '/._' '-' | tr '[:upper:]' '[:lower:]')
          echo "🧹 Cleaning up namespace: $NS"
          helm uninstall pyapp -n "$NS" || true
          kubectl delete ns "$NS" --ignore-not-found=true
