name: Cleanup vCluster on Branch Delete

on:
  delete:
    branches: ["*"]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Azure Login (client secret)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ vars.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ vars.AZURE_AKS_CLUSTER }}

      - name: Install vcluster CLI
        run: |
          curl -sSL -o vcluster "https://github.com/loft-sh/vcluster/releases/latest/download/vcluster-linux-amd64"
          chmod +x vcluster
          sudo mv vcluster /usr/local/bin/vcluster

      - name: Delete vcluster & namespace
        run: |
          NS=$(echo "${GITHUB_REF_NAME}" | tr '/._' '-' | tr '[:upper:]' '[:lower:]')
          VC="vc-${NS}"
          echo "Deleting vcluster=$VC in namespace=$NS"
          # Delete vcluster if exists
          vcluster delete "$VC" -n "$NS" --delete-namespace || true
